name: Data Fetching

on:
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: '* 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content to github runner
      - name: Checkout Code
        uses: actions/checkout@v2 

      # Install the python version needed
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' 

      # Install python packages
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Execute data preprocessing script
      - name: Execute Python script
        run: python scripts/data_fetching.py
      
      # Commit updated datasets
      - name: Commit files
        run: |
          git config --local user.email "hasaniqbal777@gmail.com"
          git config --local user.name "hasaniqbal777"
          git add -A
          git commit -m "update data" -a

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main